// <auto-generated> Сгенерировано tools/arena/train_reply.py по выгрузке replydata. Не править руками. </auto-generated>

namespace Locm
{
    /// <summary>Поправка на реальный ответ противника: E[оценка после его хода] − оценка по модели «только атаки».</summary>
    public static class ReplyModel
    {
        public const int Features = 71;
        // веса (десятитысячные): NetFeatures 0..48, oppMana/12, oppHand/8, oppDeck/30, myHand/8,
        // мой стол(3..8)×oppMana, мой стол(3..8)×oppHand, его стол(25..30)×oppMana, затем смещение
        private const string Packed = "6802,-133302,-24080,25411,3207,18228,26176,28098,17560,-10727,-2562,-15331,-37990,-4012,-21982,1152,2445,-2850,-62433,113997,14448,33518,4688,-2496,16261,-37676,-23201,-19912,3426,19707,-4231,-20484,5163,-1853,11385,-9907,5136,4765,-7163,20784,9574,32132,10302,32607,-1029,-12785,598,-25861,0,-89865,-68879,32132,-2850,11273,-16556,-5972,-16401,-30397,-3530,2048,-10578,2029,-61688,-42759,-22333,39438,45017,34070,-28233,-29057,26570,-158814";
        public static readonly double[] W = Unpack();

        private static double[] Unpack()
        {
            var parts = Packed.Split(',');
            var r = new double[parts.Length];
            for (int i = 0; i < parts.Length; i++) r[i] = int.Parse(parts[i]) / 10000.0;
            return r;
        }
    }
}
