// <auto-generated> Сгенерировано tools/arena/stats.py по пикам Legend-игроков арены. Не править руками. </auto-generated>

namespace Locm
{
    /// <summary>Рейтинг карт по драфту сильных игроков (Брэдли–Терри по предложенным тройкам), индекс — baseId.</summary>
    public static class CardTable
    {
        public const int Games = 40;
        public const int Picks = 2340;

        public static readonly double[] Rating =
        {
            0.0,
            -0.302, // 1 Slimer
            -1.808, // 2 Scuttler
            2.177, // 3 Beavrat
            -1.615, // 4 Plated Toad
            -0.337, // 5 Grime Gnasher
            -0.205, // 6 Murgling
            2.679, // 7 Rootkin Sapling
            1.596, // 8 Psyshroom
            1.984, // 9 Corrupted Beavrat
            -1.471, // 10 Carnivorous Bush
            0.263, // 11 Snowsaur
            0.003, // 12 Woodshroom
            -0.119, // 13 Swamp Terror
            -2.552, // 14 Fanged Lunger
            0.668, // 15 Pouncing Flailmouth
            -1.795, // 16 Wrangler Fish
            0.124, // 17 Ash Walker
            3.073, // 18 Acid Golem
            1.958, // 19 Foulbeast
            -1.465, // 20 Hedge Demon
            1.298, // 21 Crested Scuttler
            -2.118, // 22 Sigbovak
            2.207, // 23 Titan Cave Hog
            -2.552, // 24 Exploding Skitterbug
            -0.545, // 25 Spiney Chompleaf
            0.279, // 26 Razor Crab
            -0.944, // 27 Nut Gatherer
            1.917, // 28 Infested Toad
            2.332, // 29 Steelplume Nestling
            -1.893, // 30 Venomous Bog Hopper
            -2.630, // 31 Woodland Hunter
            2.896, // 32 Sandsplat
            2.430, // 33 Chameleskulk
            0.284, // 34 Eldritch Cyclops
            -2.165, // 35 Snail-eyed Hulker
            0.894, // 36 Possessed Skull
            2.686, // 37 Eldritch Multiclops
            -1.132, // 38 Imp
            -0.205, // 39 Voracious Imp
            -1.865, // 40 Rock Gobbler
            0.941, // 41 Blizzard Demon
            -3.011, // 42 Flying Leech
            -1.249, // 43 Screeching Nightmare
            2.748, // 44 Deathstalker
            -1.103, // 45 Night Howler
            -0.713, // 46 Soul Devourer
            -0.379, // 47 Gnipper
            2.448, // 48 Venom Hedgehog
            2.978, // 49 Shiny Prowler
            2.774, // 50 Puff Biter
            2.734, // 51 Elite Bilespitter
            1.166, // 52 Bilespitter
            2.809, // 53 Possessed Abomination
            2.190, // 54 Shadow Biter
            -3.536, // 55 Hermit Slime
            -1.010, // 56 Giant Louse
            -3.656, // 57 Dream-Eater
            -0.407, // 58 Darkscale Predator
            0.599, // 59 Sea Ghost
            -2.394, // 60 Gritsuck Troll
            -0.102, // 61 Alpha Troll
            0.066, // 62 Mutant Troll
            -2.732, // 63 Rootkin Drone
            2.242, // 64 Coppershell Tortoise
            2.863, // 65 Steelplume Defender
            2.332, // 66 Staring Wickerbeast
            2.624, // 67 Flailing Hammerhead
            3.351, // 68 Giant Squid
            2.801, // 69 Charging Boarhound
            1.707, // 70 Murglord
            -0.876, // 71 Flying Murgling
            -1.628, // 72 Shuffling Nightmare
            0.720, // 73 Bog Bounder
            -2.619, // 74 Crusher
            1.148, // 75 Titan Prowler
            -2.550, // 76 Crested Chomper
            0.496, // 77 Lumbering Giant
            -3.682, // 78 Shambler
            -0.357, // 79 Scarlet Colossus
            2.575, // 80 Corpse Guzzler
            1.641, // 81 Flying Corpse Guzzler
            2.494, // 82 Slithering Nightmare
            1.096, // 83 Restless Owl
            2.459, // 84 Fighter Tick
            2.203, // 85 Heartless Crow
            -1.206, // 86 Crazed Nose-pincher
            2.607, // 87 Bloat Demon
            2.665, // 88 Abyss Nightmare
            -2.013, // 89 Boombeak
            0.523, // 90 Eldritch Swooper
            -0.402, // 91 Flumpy
            -3.573, // 92 Wurm
            -0.026, // 93 Spinekid
            -0.421, // 94 Rootkin Defender
            2.264, // 95 Wildum
            1.619, // 96 Prairie Protector
            1.327, // 97 Turta
            -0.966, // 98 Lilly Hopper
            1.873, // 99 Cave Crab
            -2.855, // 100 Stalagopod
            -2.973, // 101 Engulfer
            -1.696, // 102 Mole Demon
            2.259, // 103 Mutating Rootkin
            0.262, // 104 Deepwater Shellcrab
            0.791, // 105 King Shellcrab
            0.522, // 106 Far-reaching Nightmare
            -0.694, // 107 Worker Shellcrab
            -0.869, // 108 Rootkin Elder
            2.192, // 109 Elder Engulfer
            -2.132, // 110 Gargoyle
            1.796, // 111 Turta Knight
            0.159, // 112 Rootkin Leader
            -3.067, // 113 Tamed Bilespitter
            1.601, // 114 Gargantua
            1.417, // 115 Rootkin Warchief
            2.271, // 116 Emperor Nightmare
            -2.926, // 117 Protein
            -0.771, // 118 Royal Helm
            -1.431, // 119 Serrated Shield
            0.483, // 120 Venomfruit
            1.756, // 121 Enchanted Hat
            0.938, // 122 Bolstering Bread
            -1.504, // 123 Wristguards
            -3.609, // 124 Blood Grapes
            -2.465, // 125 Healthy Veggies
            -0.574, // 126 Heavy Shield
            -0.952, // 127 Imperial Helm
            0.150, // 128 Enchanted Cloth
            -0.360, // 129 Enchanted Leather
            -2.474, // 130 Helm of Remedy
            -1.786, // 131 Heavy Gauntlet
            -4.058, // 132 High Protein
            0.321, // 133 Pie of Power
            0.339, // 134 Light The Way
            1.612, // 135 Imperial Armour
            -1.904, // 136 Buckler
            -1.042, // 137 Ward
            -2.123, // 138 Grow Horns
            3.095, // 139 Grow Stingers
            -3.704, // 140 Grow Wings
            0.511, // 141 Throwing Knife
            -3.563, // 142 Staff of Suppression
            -2.925, // 143 Pierce Armour
            1.736, // 144 Rune Axe
            0.914, // 145 Cursed Sword
            -2.220, // 146 Cursed Scimitar
            2.434, // 147 Quick Shot
            1.916, // 148 Helm Crusher
            -0.883, // 149 Rootkin Ritual
            1.479, // 150 Throwing Axe
            2.882, // 151 Decimate
            1.427, // 152 Mighty Throwing Axe
            -1.762, // 153 Healing Potion
            -3.538, // 154 Poison
            0.510, // 155 Scroll of Firebolt
            -2.032, // 156 Major Life Steal Potion
            1.402, // 157 Life Sap Drop
            1.696, // 158 Tome of Thunder
            -3.153, // 159 Vial of Soul Drain
            -3.328, // 160 Minor Life Steal Potion
        };
    }
}
