// <auto-generated> Сгенерировано tools/arena/stats.py по пикам Legend-игроков арены. Не править руками. </auto-generated>

namespace Locm
{
    /// <summary>Рейтинг карт по драфту сильных игроков (Брэдли–Терри по предложенным тройкам), индекс — baseId.</summary>
    public static class CardTable
    {
        public const int Games = 1474;
        public const int Picks = 71010;

        public static readonly double[] Rating =
        {
            0.0,
            -0.388, // 1 Slimer
            -2.069, // 2 Scuttler
            1.614, // 3 Beavrat
            -1.115, // 4 Plated Toad
            0.573, // 5 Grime Gnasher
            0.469, // 6 Murgling
            3.080, // 7 Rootkin Sapling
            0.958, // 8 Psyshroom
            1.605, // 9 Corrupted Beavrat
            -2.711, // 10 Carnivorous Bush
            1.229, // 11 Snowsaur
            0.722, // 12 Woodshroom
            0.192, // 13 Swamp Terror
            -1.612, // 14 Fanged Lunger
            0.904, // 15 Pouncing Flailmouth
            -1.179, // 16 Wrangler Fish
            1.181, // 17 Ash Walker
            2.685, // 18 Acid Golem
            1.659, // 19 Foulbeast
            -2.231, // 20 Hedge Demon
            1.184, // 21 Crested Scuttler
            -0.789, // 22 Sigbovak
            2.162, // 23 Titan Cave Hog
            -2.588, // 24 Exploding Skitterbug
            -0.658, // 25 Spiney Chompleaf
            0.616, // 26 Razor Crab
            -1.064, // 27 Nut Gatherer
            2.006, // 28 Infested Toad
            2.638, // 29 Steelplume Nestling
            -0.276, // 30 Venomous Bog Hopper
            -2.797, // 31 Woodland Hunter
            2.579, // 32 Sandsplat
            2.266, // 33 Chameleskulk
            0.164, // 34 Eldritch Cyclops
            -2.159, // 35 Snail-eyed Hulker
            0.346, // 36 Possessed Skull
            2.422, // 37 Eldritch Multiclops
            -0.552, // 38 Imp
            -0.337, // 39 Voracious Imp
            -1.576, // 40 Rock Gobbler
            0.272, // 41 Blizzard Demon
            -2.522, // 42 Flying Leech
            -1.681, // 43 Screeching Nightmare
            2.675, // 44 Deathstalker
            -1.108, // 45 Night Howler
            -1.828, // 46 Soul Devourer
            -0.660, // 47 Gnipper
            2.903, // 48 Venom Hedgehog
            2.958, // 49 Shiny Prowler
            2.389, // 50 Puff Biter
            2.992, // 51 Elite Bilespitter
            2.418, // 52 Bilespitter
            2.928, // 53 Possessed Abomination
            2.199, // 54 Shadow Biter
            -3.665, // 55 Hermit Slime
            -1.177, // 56 Giant Louse
            -2.897, // 57 Dream-Eater
            -1.221, // 58 Darkscale Predator
            0.126, // 59 Sea Ghost
            -2.424, // 60 Gritsuck Troll
            0.409, // 61 Alpha Troll
            -0.406, // 62 Mutant Troll
            -2.521, // 63 Rootkin Drone
            2.103, // 64 Coppershell Tortoise
            3.126, // 65 Steelplume Defender
            2.374, // 66 Staring Wickerbeast
            2.764, // 67 Flailing Hammerhead
            3.201, // 68 Giant Squid
            2.930, // 69 Charging Boarhound
            1.004, // 70 Murglord
            -1.015, // 71 Flying Murgling
            -0.269, // 72 Shuffling Nightmare
            0.272, // 73 Bog Bounder
            -0.742, // 74 Crusher
            1.291, // 75 Titan Prowler
            -1.523, // 76 Crested Chomper
            -0.000, // 77 Lumbering Giant
            -2.852, // 78 Shambler
            -0.075, // 79 Scarlet Colossus
            2.721, // 80 Corpse Guzzler
            1.113, // 81 Flying Corpse Guzzler
            2.192, // 82 Slithering Nightmare
            0.156, // 83 Restless Owl
            2.442, // 84 Fighter Tick
            1.972, // 85 Heartless Crow
            -0.184, // 86 Crazed Nose-pincher
            1.790, // 87 Bloat Demon
            1.692, // 88 Abyss Nightmare
            -0.712, // 89 Boombeak
            -0.204, // 90 Eldritch Swooper
            -0.592, // 91 Flumpy
            -3.754, // 92 Wurm
            0.033, // 93 Spinekid
            -0.639, // 94 Rootkin Defender
            1.735, // 95 Wildum
            1.503, // 96 Prairie Protector
            0.703, // 97 Turta
            -0.148, // 98 Lilly Hopper
            1.884, // 99 Cave Crab
            -0.610, // 100 Stalagopod
            -1.206, // 101 Engulfer
            -2.284, // 102 Mole Demon
            2.239, // 103 Mutating Rootkin
            0.663, // 104 Deepwater Shellcrab
            1.287, // 105 King Shellcrab
            1.183, // 106 Far-reaching Nightmare
            -2.522, // 107 Worker Shellcrab
            -1.989, // 108 Rootkin Elder
            1.657, // 109 Elder Engulfer
            -4.609, // 110 Gargoyle
            1.331, // 111 Turta Knight
            0.270, // 112 Rootkin Leader
            -3.404, // 113 Tamed Bilespitter
            1.363, // 114 Gargantua
            1.596, // 115 Rootkin Warchief
            2.877, // 116 Emperor Nightmare
            -2.960, // 117 Protein
            -0.602, // 118 Royal Helm
            -0.886, // 119 Serrated Shield
            -0.739, // 120 Venomfruit
            1.502, // 121 Enchanted Hat
            -0.246, // 122 Bolstering Bread
            -1.834, // 123 Wristguards
            -2.908, // 124 Blood Grapes
            -1.522, // 125 Healthy Veggies
            -0.118, // 126 Heavy Shield
            -1.188, // 127 Imperial Helm
            0.912, // 128 Enchanted Cloth
            0.972, // 129 Enchanted Leather
            -2.059, // 130 Helm of Remedy
            -2.432, // 131 Heavy Gauntlet
            -2.076, // 132 High Protein
            1.623, // 133 Pie of Power
            0.333, // 134 Light The Way
            0.753, // 135 Imperial Armour
            -1.813, // 136 Buckler
            -0.736, // 137 Ward
            -3.501, // 138 Grow Horns
            2.767, // 139 Grow Stingers
            -3.413, // 140 Grow Wings
            0.871, // 141 Throwing Knife
            -2.147, // 142 Staff of Suppression
            -4.184, // 143 Pierce Armour
            1.201, // 144 Rune Axe
            0.630, // 145 Cursed Sword
            -1.430, // 146 Cursed Scimitar
            1.925, // 147 Quick Shot
            1.773, // 148 Helm Crusher
            -0.869, // 149 Rootkin Ritual
            1.512, // 150 Throwing Axe
            2.982, // 151 Decimate
            1.590, // 152 Mighty Throwing Axe
            -5.242, // 153 Healing Potion
            -4.884, // 154 Poison
            0.347, // 155 Scroll of Firebolt
            -4.051, // 156 Major Life Steal Potion
            0.756, // 157 Life Sap Drop
            1.830, // 158 Tome of Thunder
            -1.137, // 159 Vial of Soul Drain
            -4.751, // 160 Minor Life Steal Potion
        };
    }
}
