// <auto-generated> Сгенерировано tools/arena/stats.py по пикам Legend-игроков арены. Не править руками. </auto-generated>

namespace Locm
{
    /// <summary>Рейтинг карт по драфту сильных игроков (Брэдли–Терри по предложенным тройкам), индекс — baseId.</summary>
    public static class CardTable
    {
        public const int Games = 1474;
        public const int Picks = 71010;

        // сотые доли рейтинга для baseId 1..160
        private const string Packed = "-39,-207,161,-111,57,47,308,96,161,-271,123,72,19,-161,90,-118,118,269,166,-223,118,-79,216,-259,-66,62,-106,201,264,-28,-280,258,227,16,-216,35,242,-55,-34,-158,27,-252,-168,268,-111,-183,-66,290,296,239,299,242,293,220,-366,-118,-290,-122,13,-242,41,-41,-252,210,313,237,276,320,293,100,-102,-27,27,-74,129,-152,0,-285,-7,272,111,219,16,244,197,-18,179,169,-71,-20,-59,-375,3,-64,173,150,70,-15,188,-61,-121,-228,224,66,129,118,-252,-199,166,-461,133,27,-340,136,160,288,-296,-60,-89,-74,150,-25,-183,-291,-152,-12,-119,91,97,-206,-243,-208,162,33,75,-181,-74,-350,277,-341,87,-215,-418,120,63,-143,192,177,-87,151,298,159,-524,-488,35,-405,76,183,-114,-475";
        private const string PackedWin = "";   // таблица с поправкой на винрейт арены (draftwin=1) — шум, из склейки убрана ради размера; восстановить: tools/arena/stats.py --win-table

        /// <summary>true — таблица с поправкой на винрейт колод (что выигрывает), false — чистые пики (что берут).</summary>
        public static bool UseWinAdjusted = false;

        /// <summary>Поправка из self-play (tools/arena/selfplay_cards.py): логит-вклад карты в победу колоды, сотые доли; пусто — нули.</summary>
        private const string PackedSelf = "-6,-13,-1,2,1,0,2,2,1,-18,3,-1,1,-6,1,1,3,2,2,-3,1,4,5,-16,0,1,-5,2,3,-2,-19,2,3,3,-1,2,4,-2,-4,-11,0,-10,-4,3,7,-1,0,2,3,2,4,2,3,2,-35,-4,-15,1,4,-3,7,7,-23,1,2,4,3,5,2,2,-3,4,-1,1,2,-5,3,-10,5,4,3,3,-2,2,0,3,0,3,-2,3,-2,-30,-4,-3,2,-1,0,-2,1,-3,-5,-9,2,1,2,2,-9,-12,2,-20,3,3,-21,4,6,5,-18,-5,-3,1,3,0,-8,-22,-3,2,1,4,4,-12,-6,-6,4,3,3,-10,1,-20,4,-17,0,-11,-32,1,2,-4,4,2,1,3,4,4,-32,-19,0,-22,2,3,-6,-38";

        public static double[] Rating => UseWinAdjusted ? _win : _pick;
        public static readonly double[] SelfPlay = PackedSelf.Length == 0 ? new double[Unpack(Packed).Length] : Unpack(PackedSelf);
        private static readonly double[] _pick = Unpack(Packed);
        private static readonly double[] _win = Unpack(PackedWin.Length == 0 ? Packed : PackedWin);

        private static double[] Unpack(string packed)
        {
            var parts = packed.Split(',');
            var r = new double[parts.Length + 1];
            for (int i = 0; i < parts.Length; i++) r[i + 1] = int.Parse(parts[i]) / 100.0;
            return r;
        }
    }
}
