#!/usr/bin/env python3
"""Генерирует src/LocmBot/Game/CardDb.cs из referee/cardlist.txt.

На CodinGame нет доступа к файлам, поэтому все 160 карт зашиты в код.
Формат строки cardlist: baseId ; name ; type ; cost ; atk ; def ; abilities ; myHp ; oppHp ; draw ; text

Запуск: python3 tools/gen_carddb.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "referee" / "cardlist.txt"
OUT = ROOT / "src" / "LocmBot" / "Game" / "CardDb.cs"

TYPES = {"creature": "CardType.Creature", "itemGreen": "CardType.GreenItem",
         "itemRed": "CardType.RedItem", "itemBlue": "CardType.BlueItem"}
FLAGS = {"B": "Breakthrough", "C": "Charge", "D": "Drain", "G": "Guard", "L": "Lethal", "W": "Ward"}


def abilities(s: str) -> str:
    names = [FLAGS[c] for c in s if c in FLAGS]
    return " | ".join("Abilities." + n for n in names) if names else "Abilities.None"


def main() -> None:
    cards = []
    for line in SRC.read_text(encoding="utf-8").splitlines():
        line = line.split("//")[0].strip()
        if not line:
            continue
        p = [x.strip() for x in line.split(";")]
        cards.append(p)
    cards.sort(key=lambda p: int(p[0]))
    assert [int(p[0]) for p in cards] == list(range(1, len(cards) + 1)), "baseId должны идти подряд с 1"

    lines = [
        "// <auto-generated> Сгенерировано tools/gen_carddb.py из referee/cardlist.txt. Не править руками. </auto-generated>",
        "",
        "namespace Locm",
        "{",
        "    /// <summary>Все карты арбитра по baseId (1..Count). У карт InstanceId = -1, Location = MyHand.</summary>",
        "    public static class CardDb",
        "    {",
        f"        public const int Count = {len(cards)};",
        "",
        "        private static readonly Card[] _cards = Build();",
        "        private static readonly string[] _names = BuildNames();",
        "",
        "        public static bool Contains(int baseId) => baseId >= 1 && baseId <= Count;",
        "",
        "        /// <summary>Карта по baseId. Бросает исключение для неизвестного id.</summary>",
        "        public static Card Get(int baseId)",
        "        {",
        "            if (!Contains(baseId)) throw new System.ArgumentOutOfRangeException(nameof(baseId), \"unknown card \" + baseId);",
        "            return _cards[baseId - 1];",
        "        }",
        "",
        "        public static string Name(int baseId) => Contains(baseId) ? _names[baseId - 1] : \"?\";",
        "",
        "        private static Card[] Build()",
        "        {",
        "            var c = new Card[Count];",
    ]
    for p in cards:
        base_id, name, typ, cost, atk, dfn, ab, my_hp, opp_hp, draw = p[:10]
        lines.append(
            f"            c[{int(base_id) - 1}] = new Card({base_id}, -1, Location.MyHand, {TYPES[typ]}, "
            f"{cost}, {atk}, {dfn}, {abilities(ab)}, {my_hp}, {opp_hp}, {draw}); // {name}")
    lines += [
        "            return c;",
        "        }",
        "",
        "        private static string[] BuildNames()",
        "        {",
        "            return new[]",
        "            {",
    ]
    for p in cards:
        lines.append(f"                \"{p[1]}\",")
    lines += [
        "            };",
        "        }",
        "    }",
        "}",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(cards)} cards")


if __name__ == "__main__":
    main()
