#!/usr/bin/env python3
"""Поправка на реальный ответ противника: target − pred ≈ f(признаки позиции после моего хода).

Данные — режим `replydata` тестового проекта (пары соседних ходов из логов арены). Модель — ридж-регрессия на
NetFeatures (49) + мана/рука/колода противника + моя рука + произведения маны и руки с признаками моего стола.
Holdout — по партиям. Печатает качество и (с --write) пишет веса в src/LocmBot/Battle/ReplyModel.cs.

  python3 tools/arena/train_reply.py build/replydata.tsv [--write] [--l2 1.0]
"""
import argparse
import re
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent.parent
NF = 49
BOARD_IDX = [3, 4, 5, 6, 7, 8]        # мой стол: count, sumA, sumD, maxA, maxD, guards (NetFeatures, сторона me)
OPP_IDX = [25, 26, 27, 28, 29, 30]    # его стол: те же признаки (смещение 22)


def build(rows):
    f = rows[:, 2:2 + NF]
    opp_mana = rows[:, 2 + NF] / 12.0
    opp_hand = rows[:, 3 + NF] / 8.0
    opp_deck = rows[:, 4 + NF] / 30.0
    my_hand = rows[:, 6 + NF] / 8.0
    cols = [f, opp_mana[:, None], opp_hand[:, None], opp_deck[:, None], my_hand[:, None]]
    cols.append(f[:, BOARD_IDX] * opp_mana[:, None])
    cols.append(f[:, BOARD_IDX] * opp_hand[:, None])
    cols.append(f[:, OPP_IDX] * opp_mana[:, None])
    return np.hstack(cols)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv")
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--l2", type=float, default=1.0)
    ap.add_argument("--out", default=str(ROOT / "src" / "LocmBot" / "Battle" / "ReplyModel.cs"))
    args = ap.parse_args()
    lines = Path(args.tsv).read_text().splitlines()
    header = lines[0].split("\t")
    games = []
    data = []
    for line in lines[1:]:
        p = line.split("\t")
        games.append(p[0])
        data.append([float(x) for x in p[1:]])
    rows = np.array(data)
    games = np.array(games)
    hdr = {name: i - 1 for i, name in enumerate(header)}   # индексы в rows (без game)
    pred = rows[:, hdr["pred"]]
    stat = rows[:, hdr["static"]]
    target = rows[:, hdr["target"]]
    died = rows[:, hdr["died"]] > 0
    resid = target - pred
    print(f"{len(rows)} rows, deaths {died.sum()}; pred vs target: MAE {np.mean(np.abs(resid)):.2f}, mean resid {resid.mean():+.2f}, "
          f"corr(pred,target) {np.corrcoef(pred, target)[0, 1]:.3f}; static vs target: MAE {np.mean(np.abs(target - stat)):.2f}")
    # признаки: NetFeatures начинаются со столбца 'f0'
    # build() ждёт: [turn, ?, f0..f48, oppMana, oppHand, oppDeck, myDraw, myHand]
    X = build(np.hstack([rows[:, :1], rows[:, :1], rows[:, hdr["f0"]:hdr["f0"] + NF],
                         rows[:, [hdr["oppMana"], hdr["oppHand"], hdr["oppDeck"], hdr["myDraw"], hdr["myHand"]]]]))
    # holdout по партиям
    uniq = np.unique(games)
    rng = np.random.default_rng(3)
    test_games = set(rng.choice(uniq, size=len(uniq) // 5, replace=False))
    te = np.array([g in test_games for g in games])
    tr = ~te
    mu = X[tr].mean(axis=0)
    sd = X[tr].std(axis=0) + 1e-9
    Z = (X - mu) / sd
    y = resid
    A = Z[tr].T @ Z[tr] + args.l2 * len(tr) / 100.0 * np.eye(Z.shape[1])
    w = np.linalg.solve(A, Z[tr].T @ (y[tr] - y[tr].mean()))
    b = y[tr].mean()
    yhat = Z @ w + b
    for name, m in (("train", tr), ("holdout", te)):
        base = np.mean((y[m] - 0) ** 2)
        mse = np.mean((y[m] - yhat[m]) ** 2)
        print(f"  {name}: residual var {base:.2f} -> after model {mse:.2f} (R2 {1 - mse / base:.3f}); "
              f"MAE pred {np.mean(np.abs(y[m])):.2f} -> corrected {np.mean(np.abs(y[m] - yhat[m])):.2f}")
    # без смертей (они доминируют в хвосте)
    m = te & ~died
    print(f"  holdout without deaths: MAE pred {np.mean(np.abs(y[m])):.2f} -> corrected {np.mean(np.abs(y[m] - yhat[m])):.2f}, "
          f"corr(yhat, y) {np.corrcoef(yhat[m], y[m])[0, 1]:.3f}")
    # веса в исходном масштабе
    w_raw = w / sd
    b_raw = b - w_raw @ mu
    names = [f"f{i}" for i in range(NF)] + ["oppMana", "oppHand", "oppDeck", "myHand"] + \
            [f"myBoard{i}*mana" for i in BOARD_IDX] + [f"myBoard{i}*hand" for i in BOARD_IDX] + [f"oppBoard{i}*mana" for i in OPP_IDX]
    order = np.argsort(-np.abs(w))
    print("  top weights (standardized):", " ".join(f"{names[i]}={w[i]:+.2f}" for i in order[:12]))
    print(f"  bias {b_raw:+.3f}")
    if args.write:
        packed = ",".join(str(int(round(v * 10000))) for v in np.concatenate([w_raw, [b_raw]]))
        text = f'''// <auto-generated> Сгенерировано tools/arena/train_reply.py по выгрузке replydata. Не править руками. </auto-generated>

namespace Locm
{{
    /// <summary>Поправка на реальный ответ противника: E[оценка после его хода] − оценка по модели «только атаки».</summary>
    public static class ReplyModel
    {{
        public const int Features = {len(w_raw)};
        // веса (десятитысячные): NetFeatures 0..48, oppMana/12, oppHand/8, oppDeck/30, myHand/8,
        // мой стол(3..8)×oppMana, мой стол(3..8)×oppHand, его стол(25..30)×oppMana, затем смещение
        private const string Packed = "{packed}";
        public static readonly double[] W = Unpack();

        private static double[] Unpack()
        {{
            var parts = Packed.Split(',');
            var r = new double[parts.Length];
            for (int i = 0; i < parts.Length; i++) r[i] = int.Parse(parts[i]) / 10000.0;
            return r;
        }}
    }}
}}
'''
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"weights -> {args.out} ({len(packed)} chars)")


if __name__ == "__main__":
    sys.exit(main())
